version: 2

requirements:
  signed_off_by:
    required: false

group_defaults:
  required: 1
  approve_by_comment:
    enabled: true
    approve_regex: '^(lgtm|LGTM)'
    reject_regex: ^Rejected
  reset_on_push:
    enabled: true
  author_approval:
    ignored: true
  conditions:
    branches:
      - master

groups:
  maintainers:
    teams:
      - maintainers
