version: 2

group_defaults:
  required: 1
  approve_by_comment:
    enabled: true
    approve_regex: '^(lgtm|LGTM)'
  reset_on_push:
    enabled: true
  author_approval:
    ignored: true
  conditions:
    branches:
      - master

groups:
  maintainers:
    teams:
      - maintainers
